version: '3.8'

services:
  frontend:
    container_name: frontend-club-navigation
    ports:
      - "3000:80"
    build:
      context: ./map-navigation
    depends_on:
      - backend
    networks:
      - club-network

  backend:
    container_name: backend-club-navigation
    ports:
      - "5000:5000"
    build:
      context: ./server
    restart: always
    networks:
      - club-network

networks:
  club-network:
    driver: bridge
