version: '3'

services:
  frontend:
    image: node:20-alpine
    container_name: frontend-club-navigation
    working_dir: /app
    ports:
      - "3000:80"
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      apk add --no-cache git &&
      git clone https://github.com/BrayanSGL/air-traffic-manager.git &&
      cd air-traffic-manager &&
      npm install &&
      npm run build &&
      npm install -g serve &&
      serve -s build"
    restart: always
    