FLIGHTS = [
  {
    "id": 1,
    "name": "Aeropuerto Internacional El Dorado",
    "code": "BOG",
    "coordinates": [4.7, -74.15],
    "departure": "08:00",
    "flightTime": 90,
    "waitTime": 30, 
  },
  {
    "id": 2,
    "name": "Aeropuerto Internacional Alfonso Bonilla Aragón",
    "code": "CLO",
    "coordinates": [3.45, -76.53],
    "departure": "10:30",
    "flightTime": 75,
    "waitTime": 20,
  },
  {
    "id": 3,
    "name": "Aeropuerto Internacional José María Córdova",
    "code": "MDE",
    "coordinates": [6.22, -75.59],
    "departure": "12:25",
    "flightTime": 105, 
    "waitTime": 25, 
  },
  {
    "id": 4,
    "name": "Aeropuerto Internacional Rafael Núñez",
    "code": "CTG",
    "coordinates": [10.44, -75.51],
    "departure": "14:00",
    "flightTime": 90, 
    "waitTime": 15, 
  },
  {
    "id": 5,
    "name": "Aeropuerto Internacional Palonegro",
    "code": "BGA",
    "coordinates": [7.13, -73.18],
    "departure": "17:00",
    "flightTime": 120, 
    "waitTime": 30, 
  },
  {
    "id": 6,
    "name": "Aeropuerto Alfredo Vásquez Cobo",
    "code": "LET",
    "coordinates": [-4.19, -69.94],
    "departure": "20:00",
    "flightTime": 150, 
    "waitTime": 15,
  },
  {
    "id": 7,
    "name": "Aeropuerto Internacional El Dorado",
    "code": "BOG",
    "coordinates": [4.7, -74.15],
    "departure": "00:00",
    "flightTime": 150,
    "waitTime": 0,
  }
]