DESTINATIONS = [
  {
    "id": 1,
    "name": "Aeropuerto Internacional El Dorado",
    "code": "BOG",
    "coordinates": [4.7, -74.15],
    "flightTime": 169,
    "waitTime": 30,
    "totalTime": 199,
  },
  {
    "id": 2,
    "name": "Aeropuerto Internacional Alfonso Bonilla Aragón",
    "code": "CLO",
    "coordinates": [3.45, -76.53],
    "flightTime": 141,
    "waitTime": 20,
    "totalTime": 161,
  },
  {
    "id": 3,
    "name": "Aeropuerto Internacional José María Córdova",
    "code": "MDE",
    "coordinates": [6.22, -75.59],
    "flightTime": 197, 
    "waitTime": 25,
    "totalTime": 222,
  },
  {
    "id": 4,
    "name": "Aeropuerto Internacional Rafael Núñez",
    "code": "CTG",
    "coordinates": [10.44, -75.51],
    "flightTime": 169, 
    "waitTime": 15,
    "totalTime": 184,
  },
  {
    "id": 5,
    "name": "Aeropuerto Internacional Palonegro",
    "code": "BGA",
    "coordinates": [7.13, -73.18],
    "flightTime": 225, 
    "waitTime": 30,
    "totalTime": 255,
  },
  {
    "id": 6,
    "name": "Aeropuerto Alfredo Vásquez Cobo",
    "code": "LET",
    "coordinates": [-4.19, -69.94],
    "flightTime": 282,
    "waitTime": 15,
    "totalTime": 297,
  },
]